spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ieum?&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # application 첫 실행 시에만 create, 이후에는 none 혹은 주석처리
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

springdoc:
  version: '0.0.1'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**
logging:
  level:
    root: INFO
    org.example.backend.controller: DEBUG  # StoryController가 있는 패키지
    org.springframework: INFO
    org.springframework.security: DEBUG  # 시큐리티 관련 로그
    org.springframework.web: DEBUG